"""Stage 1 — snapshot tests.

Covers section 8 AC1-AC5: complete discovery, stable hashes, content
sensitivity, non-source filtering, deterministic manifest.
"""

from __future__ import annotations

import unittest

from maat.core.enums import FileKind, ParseStatus
from maat.offline.snapshot import SnapshotOptions, scan_repository

from ..support import DEMO_REPO, temp_repo


class SnapshotDiscoveryTests(unittest.TestCase):
    """AC1 — complete discovery."""

    def test_finds_every_source_file(self) -> None:
        snapshot = scan_repository(DEMO_REPO, model_version="mv_test")
        paths = sorted(record.path for record in snapshot.files)
        self.assertEqual(
            paths,
            [
                "api/checkout_controller.py",
                "broken/broken_service.py",
                "models/payment.py",
                "repositories/payment_repository.py",
                "services/checkout_service.py",
                "services/payment_service.py",
                "services/refund_service.py",
            ],
        )

    def test_language_detected_for_every_source_file(self) -> None:
        snapshot = scan_repository(DEMO_REPO, model_version="mv_test")
        for record in snapshot.files:
            self.assertEqual(record.language, "python", record.path)
            self.assertEqual(record.file_kind, FileKind.SOURCE)


class SnapshotHashTests(unittest.TestCase):
    """AC2 — stable hashes. AC3 — content sensitivity."""

    def test_hashes_are_stable_across_runs(self) -> None:
        first = scan_repository(DEMO_REPO, model_version="mv_a")
        second = scan_repository(DEMO_REPO, model_version="mv_b")
        self.assertEqual(
            {r.path: r.content_hash for r in first.files},
            {r.path: r.content_hash for r in second.files},
        )

    def test_content_change_changes_the_hash(self) -> None:
        with temp_repo({"a.py": "value = 1\n"}) as root:
            before = scan_repository(root, model_version="mv").files[0].content_hash
            (root / "a.py").write_text("value = 2\n", encoding="utf-8")
            after = scan_repository(root, model_version="mv").files[0].content_hash
        self.assertNotEqual(before, after)

    def test_line_ending_change_changes_the_hash(self) -> None:
        """Raw-byte hashing means a CRLF rewrite is a real change.

        It changes what the parser sees, so treating it as unchanged would let
        the model drift from the file on disk.
        """
        with temp_repo({"a.py": b"value = 1\n"}) as root:
            before = scan_repository(root, model_version="mv").files[0].content_hash
            (root / "a.py").write_bytes(b"value = 1\r\n")
            after = scan_repository(root, model_version="mv").files[0].content_hash
        self.assertNotEqual(before, after)

    def test_whitespace_only_edit_changes_the_hash(self) -> None:
        with temp_repo({"a.py": "value = 1\n"}) as root:
            before = scan_repository(root, model_version="mv").files[0].content_hash
            (root / "a.py").write_text("value = 1\n\n", encoding="utf-8")
            after = scan_repository(root, model_version="mv").files[0].content_hash
        self.assertNotEqual(before, after)


class SnapshotFilteringTests(unittest.TestCase):
    """AC4 — non-source filtering."""

    def test_binary_generated_and_ignored_files_are_excluded(self) -> None:
        files = {
            "src/real.py": "value = 1\n",
            "src/generated_pb2.py": "# Code generated by protoc. DO NOT EDIT.\nx = 1\n",
            "src/bundle.min.js": "var a=1;\n",
            "src/blob.dat": b"\x00\x01\x02binary\x00",
            "src/payload": b"\x00\x01binary\x00\xff",  # no extension: content sniffed
            "node_modules/dep/index.js": "module.exports = {};\n",
            "build/out.py": "value = 1\n",
            ".git/config": b"[core]\n",
            "README.md": "# hi\n",
        }
        with temp_repo(files) as root:
            snapshot = scan_repository(root, model_version="mv")
            kept = {record.path for record in snapshot.files}
            reasons = {record.path: record.reason for record in snapshot.excluded}

        self.assertIn("src/real.py", kept)
        self.assertIn("README.md", kept)  # non-code but not excluded
        self.assertNotIn("src/generated_pb2.py", kept)
        self.assertNotIn("src/bundle.min.js", kept)
        self.assertNotIn("src/blob.dat", kept)
        self.assertNotIn("src/payload", kept)
        self.assertNotIn("node_modules/dep/index.js", kept)
        self.assertNotIn("build/out.py", kept)

        self.assertEqual(reasons["src/generated_pb2.py"], FileKind.GENERATED)
        self.assertEqual(reasons["src/bundle.min.js"], FileKind.GENERATED)
        self.assertEqual(reasons["src/blob.dat"], FileKind.IGNORED)
        # Content-sniffed binary: proves detection is not name-based.
        self.assertEqual(reasons["src/payload"], FileKind.BINARY)
        self.assertEqual(reasons["node_modules"], FileKind.IGNORED)

    def test_pruned_directories_are_reported(self) -> None:
        """A silently skipped directory is indistinguishable from a missing one."""
        with temp_repo({"node_modules/x/y.js": "var a=1;\n", "src/a.py": "x = 1\n"}) as root:
            snapshot = scan_repository(root, model_version="mv")
        reported = {record.path for record in snapshot.excluded}
        self.assertIn("node_modules", reported)

    def test_non_code_language_is_unsupported_not_source(self) -> None:
        with temp_repo({"data/config.json": '{"a": 1}\n'}) as root:
            snapshot = scan_repository(root, model_version="mv")
        record = snapshot.files[0]
        self.assertEqual(record.file_kind, FileKind.UNSUPPORTED)
        self.assertEqual(record.parse_status, ParseStatus.UNSUPPORTED)

    def test_unknown_extension_is_unsupported(self) -> None:
        with temp_repo({"a.xyzzy": "hello\n"}) as root:
            snapshot = scan_repository(root, model_version="mv")
        record = snapshot.files[0]
        self.assertIsNone(record.language)
        self.assertEqual(record.parse_status, ParseStatus.UNSUPPORTED)

    def test_empty_source_file_is_empty_not_failed(self) -> None:
        with temp_repo({"a.py": b""}) as root:
            snapshot = scan_repository(root, model_version="mv")
        self.assertEqual(snapshot.files[0].parse_status, ParseStatus.EMPTY)

    def test_ignoring_can_be_disabled(self) -> None:
        with temp_repo({"node_modules/x/y.js": "var a=1;\n"}) as root:
            snapshot = scan_repository(
                root,
                model_version="mv",
                options=SnapshotOptions(ignore_directories=frozenset()),
            )
        self.assertEqual([r.path for r in snapshot.files], ["node_modules/x/y.js"])


class SnapshotDeterminismTests(unittest.TestCase):
    """AC5 — deterministic snapshot."""

    def test_manifest_is_byte_identical_across_runs(self) -> None:
        from maat.core.serialization import canonical_json
        from maat.offline.snapshot import manifest_payload

        first = scan_repository(DEMO_REPO, model_version="mv")
        second = scan_repository(DEMO_REPO, model_version="mv")
        self.assertEqual(
            canonical_json(manifest_payload(first)),
            canonical_json(manifest_payload(second)),
        )

    def test_files_are_sorted_by_path(self) -> None:
        snapshot = scan_repository(DEMO_REPO, model_version="mv")
        paths = [record.path for record in snapshot.files]
        self.assertEqual(paths, sorted(paths))

    def test_records_carry_the_requested_version(self) -> None:
        snapshot = scan_repository(DEMO_REPO, model_version="mv_x")
        self.assertTrue(all(r.model_version == "mv_x" for r in snapshot.files))

    def test_non_directory_raises(self) -> None:
        with self.assertRaises(NotADirectoryError):
            scan_repository(DEMO_REPO / "models" / "payment.py", model_version="mv")


if __name__ == "__main__":
    unittest.main()
