"""Stage 1 — repository snapshot (spec section 8).

Produces a stable, deterministic file manifest: the same repository state must
yield the same manifest, byte for byte, on any machine (section 8 AC5).

Determinism is achieved by never trusting the filesystem's order. ``os.walk``
yields directory and file names in arbitrary order, so both are sorted before
use, and the final manifest is sorted by path. Anything that varies between
runs -- mtimes, inode numbers, absolute paths -- is kept out of the output.

Files that are ignored, binary or generated are *excluded* from the manifest
(section 8 AC4) but recorded in ``snapshot.excluded`` with a reason, so
"why is my file missing?" always has an answer.
"""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from ..core.contracts import ExcludedFile, FileRecord, RepositorySnapshot
from ..core.enums import FileKind, ParseStatus
from . import languages

#: Directory names skipped entirely, matched case-insensitively at any depth.
IGNORED_DIRECTORIES: frozenset[str] = frozenset(
    {
        ".git", ".hg", ".svn", ".bzr",
        "node_modules", "bower_components", "jspm_packages",
        "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox",
        ".venv", "venv", "env", ".env", "virtualenv",
        "site-packages", "dist-packages", "eggs",
        "dist", "build", "out", "target", "bin", "obj",
        ".idea", ".vscode", ".vs", ".settings",
        ".next", ".nuxt", ".svelte-kit", ".parcel-cache", ".turbo",
        ".gradle", ".m2", ".terraform", ".serverless", ".cache",
        "coverage", "htmlcov", ".nyc_output", "vendor", "third_party",
        "Pods", "DerivedData", ".dart_tool", ".pub-cache",
        # MAAT's own index directory. Without this the index would be scanned
        # on the next run and would grow the repository every time it indexed.
        ".maat",
    }
)

#: File name suffixes skipped entirely.
IGNORED_SUFFIXES: frozenset[str] = frozenset(
    {
        ".lock", ".log", ".tmp", ".temp", ".bak", ".orig", ".rej", ".swp",
        ".pyc", ".pyo", ".pyd", ".class", ".o", ".obj", ".a", ".lib",
        ".so", ".dylib", ".dll", ".exe", ".wasm",
        ".jar", ".war", ".ear", ".nupkg", ".whl", ".egg",
        ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".svg",
        ".pdf", ".psd", ".ai", ".eps",
        ".mp3", ".mp4", ".wav", ".avi", ".mov", ".mkv",
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        ".db", ".sqlite", ".sqlite3", ".mdb", ".pdb",
        ".bin", ".dat", ".iso", ".dmg", ".pkl", ".npy", ".npz", ".parquet",
    }
)

#: Exact file names skipped entirely.
IGNORED_FILENAMES: frozenset[str] = frozenset(
    {
        ".DS_Store", "Thumbs.db", "desktop.ini",
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "composer.lock",
        "poetry.lock", "Pipfile.lock", "Cargo.lock", "Gemfile.lock", "go.sum",
    }
)

#: Path fragments that mark a file as machine-generated.
#:
#: Deliberately conservative. A false positive here silently removes real
#: source from the model, which is far worse than a false negative that merely
#: leaves generated code in it -- the model can be queried about generated code,
#: but it can never be queried about code that was never indexed.
#:
#: ``/gen/`` is specifically excluded. It reads like "generated" but is also a
#: common ordinary package segment (``com/example/gen``), and using it silently
#: dropped every Java file under such a package during testing.
GENERATED_PATH_MARKERS: tuple[str, ...] = (
    "/generated/", "/autogen/", "/auto-generated/", "/__generated__/",
    "/gen-code/", "/generated-sources/",
)

#: File name suffixes that mark a file as machine-generated.
GENERATED_SUFFIXES: tuple[str, ...] = (
    "_pb2.py", "_pb2_grpc.py", ".pb.go", ".pb.cc", ".pb.h",
    ".g.cs", ".designer.cs", ".generated.cs", ".min.js", ".min.css",
    ".freezed.dart", ".g.dart", "_generated.go",
)

#: Markers searched for in the first few KB of a file.
GENERATED_CONTENT_MARKERS: tuple[bytes, ...] = (
    b"@generated", b"DO NOT EDIT", b"do not edit", b"Code generated by",
    b"code generated by", b"automatically generated", b"Auto-generated",
    b"THIS FILE IS AUTO-GENERATED",
)

#: How many bytes to read when sniffing binary/generated content.
SNIFF_BYTES = 8192


@dataclass(frozen=True)
class SnapshotOptions:
    """Knobs for a scan. Defaults match the spec's expectations."""

    ignore_directories: frozenset[str] = IGNORED_DIRECTORIES
    ignore_suffixes: frozenset[str] = IGNORED_SUFFIXES
    ignore_filenames: frozenset[str] = IGNORED_FILENAMES
    detect_generated: bool = True
    detect_binary: bool = True


def _now_iso() -> str:
    """Wall-clock timestamp for snapshot metadata.

    Never written into a ``FileRecord``, and never part of the model digest, so
    it cannot break determinism.
    """
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _hash_bytes(data: bytes) -> str:
    """SHA-256 over raw bytes.

    Raw bytes, not decoded text, for three reasons: it is encoding-independent
    (a Latin-1 and a UTF-8 file with the same characters hash differently, which
    is correct -- they are different bytes); it cannot fail on undecodable
    input; and it is sensitive to line-ending changes, which do change what a
    parser sees.
    """
    return "sha256:" + hashlib.sha256(data).hexdigest()


def _looks_binary(head: bytes) -> bool:
    """NUL byte in the first few KB means binary.

    The same heuristic git uses. Cheap, and it never misclassifies real source
    code, because no text encoding this pipeline accepts emits NUL.
    """
    return b"\x00" in head


def _looks_generated(relative_path: str, head: bytes, options: SnapshotOptions) -> bool:
    lowered = relative_path.lower()
    if any(marker in lowered for marker in GENERATED_PATH_MARKERS):
        return True
    if any(lowered.endswith(suffix) for suffix in GENERATED_SUFFIXES):
        return True
    return any(marker in head for marker in GENERATED_CONTENT_MARKERS)


def _is_ignored_path(relative_path: str, options: SnapshotOptions) -> bool:
    name = relative_path.rsplit("/", 1)[-1]
    if name in options.ignore_filenames:
        return True
    lowered = name.lower()
    for suffix in options.ignore_suffixes:
        if lowered.endswith(suffix):
            return True
    return False


def _read_head(path: Path) -> bytes:
    with open(path, "rb") as stream:
        return stream.read(SNIFF_BYTES)


def _iter_files(
    root: Path, options: SnapshotOptions
) -> tuple[list[str], list[str], list[str]]:
    """Walk ``root`` deterministically.

    Returns ``(source_paths, ignored_file_paths, pruned_directory_paths)``, all
    sorted. Sorting at every level is what makes the walk order-independent.

    Pruned directories are returned rather than discarded so the snapshot can
    report them. A silently skipped directory is indistinguishable from a
    directory that does not exist, and "why is my code missing?" is a question
    the manifest should be able to answer.
    """
    kept: list[str] = []
    ignored: list[str] = []
    pruned: list[str] = []

    for current_dir, dir_names, file_names in os.walk(root):
        # In-place sort: os.walk uses this list to decide traversal order.
        dir_names.sort()
        file_names.sort()

        # Prune ignored directories in place so os.walk does not descend.
        keep_dirs: list[str] = []
        for directory in dir_names:
            if directory.lower() in options.ignore_directories:
                pruned.append(
                    (Path(current_dir) / directory).relative_to(root).as_posix()
                )
            else:
                keep_dirs.append(directory)
        dir_names[:] = keep_dirs

        for file_name in file_names:
            absolute = Path(current_dir) / file_name
            relative = absolute.relative_to(root).as_posix()
            if _is_ignored_path(relative, options):
                ignored.append(relative)
            else:
                kept.append(relative)

    return sorted(kept), sorted(ignored), sorted(pruned)


def scan_repository(
    root: str | Path,
    model_version: str,
    options: SnapshotOptions | None = None,
) -> RepositorySnapshot:
    """Scan ``root`` and return a deterministic snapshot.

    Never raises for a file-level problem: an unreadable or disappearing file
    becomes a ``FAILED`` record with the reason attached, because section 30
    AC1 forbids one bad file from stopping repository indexing.
    """
    options = options or SnapshotOptions()
    root_path = Path(root).resolve()
    if not root_path.is_dir():
        raise NotADirectoryError(f"not a repository directory: {root_path}")

    candidates, ignored_paths, pruned_dirs = _iter_files(root_path, options)

    files: list[FileRecord] = []
    excluded: list[ExcludedFile] = [
        ExcludedFile(path=p, reason=FileKind.IGNORED, size=0) for p in ignored_paths
    ]
    excluded.extend(
        ExcludedFile(path=p, reason=FileKind.IGNORED, size=0) for p in pruned_dirs
    )

    for relative in candidates:
        absolute = root_path / relative
        try:
            data = absolute.read_bytes()
        except OSError as error:
            files.append(
                FileRecord(
                    path=relative,
                    language=languages.detect_language(relative),
                    content_hash="",
                    size=0,
                    parse_status=ParseStatus.FAILED,
                    parse_error=f"unreadable: {error.strerror or error}",
                    model_version=model_version,
                    file_kind=FileKind.SOURCE,
                )
            )
            continue

        size = len(data)
        head = data[:SNIFF_BYTES]
        language = languages.detect_language(relative)

        if options.detect_binary and _looks_binary(head):
            excluded.append(
                ExcludedFile(path=relative, reason=FileKind.BINARY, size=size)
            )
            continue

        if options.detect_generated and _looks_generated(relative, head, options):
            excluded.append(
                ExcludedFile(path=relative, reason=FileKind.GENERATED, size=size)
            )
            continue

        is_code = languages.is_code_language(language)

        if language is None:
            file_kind = FileKind.UNSUPPORTED
            parse_status = ParseStatus.UNSUPPORTED
        elif not is_code:
            file_kind = FileKind.UNSUPPORTED
            parse_status = ParseStatus.UNSUPPORTED
        elif size == 0:
            file_kind = FileKind.SOURCE
            parse_status = ParseStatus.EMPTY
        else:
            file_kind = FileKind.SOURCE
            # Provisional. The parser stage refines this to OK, PARTIAL or
            # FAILED; snapshotting cannot know whether the syntax is valid.
            parse_status = ParseStatus.OK

        files.append(
            FileRecord(
                path=relative,
                language=language,
                content_hash=_hash_bytes(data),
                size=size,
                parse_status=parse_status,
                parse_error=None,
                model_version=model_version,
                file_kind=file_kind,
                is_binary=False,
                is_generated=False,
                line_count=data.count(b"\n") + (1 if data and not data.endswith(b"\n") else 0),
            )
        )

    files.sort(key=lambda record: record.path)
    excluded.sort(key=lambda record: record.path)

    return RepositorySnapshot(
        root=str(root_path),
        model_version=model_version,
        files=files,
        excluded=excluded,
        taken_at=_now_iso(),
    )


def manifest_payload(snapshot: RepositorySnapshot) -> dict[str, object]:
    """The subset of a snapshot persisted as the change-detection manifest.

    Only path and content hash are needed to detect changes, so only those are
    stored. Keeping the manifest small keeps it cheap to read on every run.
    """
    return {
        "model_version": snapshot.model_version,
        "taken_at": snapshot.taken_at,
        "entries": [
            {
                "path": record.path,
                "content_hash": record.content_hash,
                "language": record.language,
                "size": record.size,
            }
            for record in snapshot.files
        ],
    }
